### ISSUE TITLE
Cannot open Piglets solution

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellifactory/websharper.piglets#4]
The imported project "L:\git\websharper.piglets\build\net45\IntelliFactory.WebSharper.Piglets.proj" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  L:\git\websharper.piglets\Piglets\IntelliFactory.WebSharper.Piglets.fsproj

**Comment by radekm** [comment]
It seems that after running `build.cmd` you have to modify project files by replacing `WebSharper.2.5.119.54` by the name of the subfolder which has been created in `packages` folder (for me it was `WebSharper.3.0.12.88-alpha`).

**Comment by Tarmil** [comment]
You need to run build.cmd to generate the .proj indeed. For the second issue, project files have since been updated to not need such updates anymore, everything version-specific is contained in the build.cmd-generated .proj file.
