### ISSUE TITLE
Why SubscribeImmediate

### ISSUE THREAD

**Issue by davidgrenier** [intellifactory/websharper.piglets#8]
Hello,

I still do not understand why you have SubscribeImmediate when you depend on HotStream.Subscribe which already propagates the current value? This was problematic for us in that we had to rewrite a bunch of combinators that wouldn't push extra values to the back end...

**Comment by Tarmil** [comment]
Indeed, I think previously HotStream didn't always propagate the current value. SubscribeImmediate is now obsolete, I marked it as such and made its implementation equivalent to Subscribe.
